- hosts: appserver
  become: yes
  tasks:
    - name: Pull latest app image
      docker_container:
        name: devops_app
        image: kartikmaha/devops-app:latest
        state: absent
        pull: true
        restart_policy: always
        ports:
          - "5000:5000"
