- hosts: appserver
  become: yes
  tasks:

    - name: Stop and remove existing app container
      docker_container:
        name: devops_app
        state: absent

    - name: Pull and run latest app image
      docker_container:
        name: devops_app
        image: kartikmaha/devops-app:latest
        state: started
        recreate: yes
        pull: true
        restart_policy: always
        ports:
          - "80:5000"
